import resolve from '@rollup/plugin-node-resolve';

export default {
  input: 'src/index.js',
  output: {
    file: 'zen-pomodoro-focus-blocker.uc.js',
    format: 'iife',
    // No 'name' needed since this is a self-executing function with no exports
    // The IIFE wrapper is added by rollup automatically
    globals: {
      // Firefox/Browser globals - these are available at runtime
      Services: 'Services',
      Components: 'Components',
      ChromeUtils: 'ChromeUtils',
    },
    banner: `/**
 * Zen Pomodoro Focus Blocker Mod
 * Version: 1.4.4
 * License: MIT
 *
 * A productivity mod that implements customizable Pomodoro timer with workspace blocking
 *
 * BUNDLED WITH ROLLUP - DO NOT EDIT THIS FILE DIRECTLY
 * Edit source files in src/ directory and rebuild with: npm run build
 */`,
  },
  plugins: [resolve()],
  // External dependencies - these are provided by the Firefox runtime
  external: ['Services', 'Components', 'ChromeUtils'],
  // Suppress warnings about browser/DOM globals
  onwarn(warning, warn) {
    // Ignore warnings about eval, circular dependencies, and export mixing
    if (
      warning.code === 'EVAL' ||
      warning.code === 'CIRCULAR_DEPENDENCY' ||
      warning.code === 'MISSING_NAME_OPTION_FOR_IIFE_EXPORT' ||
      (warning.code === 'MIXED_EXPORTS' && warning.id?.includes('src/index.js'))
    ) {
      return;
    }
    warn(warning);
  },
};
